dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: eO+Di93DR00MisY4nQeXakiyYHs/dbCAXVcEfGEmLTO62YjyqKNkD0KoSqGZhI77P3K7XbqtyOBxrkVSIDXA2oogIqe5BF+PqIPwtWulQLDX6rW+I2TC6ybjA3uoGQ2GBpIKxVbTQq875hi5l3WivYcEMAFzm0XazM0D2gFESMRNx0vZIeDtR7ld07M4cpcmcF6xMAVdqUaqynaQEHwLmZLkLjbwh97yNzU0EQd7tzb/c2SfmLVMGDgT/RgTdYbDCy+eOZublrm0tQQ4bH1F1MGrcDk7U6qoht7Jm3YXAoGWsa55w8pz+elfR9f//PmF+Owe3V5vDktPCiFoEk+DcY6uWY8XWmM1rkkPvRGwhdXTYm8/uv7XqyyGKhdfI+3jeiTk9bupIXhNSH6ztUuuI++hc9ic2IyWpy62edCWW6Z9EqclrQvpmGDjh8rVA5BIkZkfFhYHXfvll63VObpqEdYCg4q+tzBBXy2CWyMi9sgVYhdJk2MNcKIALcYM8tJcqo/PbYyyW3kxiXTlMshZlKr9FsUVWEzxs47Tw1nI45Ya+EthJ0y/k/zPqqGdMn+01CwxC46KHeFPaev+RlRsA3L5Hy/eqR1oC1dSpPEjoIgtchLawfcUfS3iDggHaqTS2xuxe9X9Q3UMdqvxLrZ9e4vLUFW5dQ0ijAL/qzf3tZc=
install:
- pip install -r requirements.txt
- pip install pylint circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint adafruit_si4713.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name,bad-whitespace
  examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-si4713 --library_location
  .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
